// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvnimTDn6FDLxSbSKBZxiI-Qf37FXYdrg',
    appId: '1:963869250426:web:74ca9a354d722f16f67cc3',
    messagingSenderId: '963869250426',
    projectId: 'marvelapp-ba95e',
    authDomain: 'marvelapp-ba95e.firebaseapp.com',
    storageBucket: 'marvelapp-ba95e.appspot.com',
    measurementId: 'G-GBDP9LQ8T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBotHiBBB5OjjcgedZc8pFl9uWhtM7P850',
    appId: '1:963869250426:android:af13546935dfc95af67cc3',
    messagingSenderId: '963869250426',
    projectId: 'marvelapp-ba95e',
    storageBucket: 'marvelapp-ba95e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7ESxQA0JzJ3-n23Liq-0LM4ZjxbreJQ',
    appId: '1:963869250426:ios:650cc5a49ac58f2cf67cc3',
    messagingSenderId: '963869250426',
    projectId: 'marvelapp-ba95e',
    storageBucket: 'marvelapp-ba95e.appspot.com',
    iosBundleId: 'com.example.marvelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7ESxQA0JzJ3-n23Liq-0LM4ZjxbreJQ',
    appId: '1:963869250426:ios:650cc5a49ac58f2cf67cc3',
    messagingSenderId: '963869250426',
    projectId: 'marvelapp-ba95e',
    storageBucket: 'marvelapp-ba95e.appspot.com',
    iosBundleId: 'com.example.marvelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvnimTDn6FDLxSbSKBZxiI-Qf37FXYdrg',
    appId: '1:963869250426:web:faf33b0362c876fbf67cc3',
    messagingSenderId: '963869250426',
    projectId: 'marvelapp-ba95e',
    authDomain: 'marvelapp-ba95e.firebaseapp.com',
    storageBucket: 'marvelapp-ba95e.appspot.com',
    measurementId: 'G-P9M3R6PGSV',
  );
}
